// src/app/entries/entries.component.ts
import { Component, OnInit } from '@angular/core';
import { JdsClientService, DatabaseInformation } from '../shared/jds-client.service';
import { Entry } from "../shared/entry/entry";
import { EntryService } from "../shared/entry/entry.service";
import { FormBuilder, Validators } from "@angular/forms";
import { BTreeModificationResult, BTreeNode, RemoteBTree } from "../shared/remote-b-tree";

@Component({
  selector: 'app-entries',
  templateUrl: './entries.component.html',
  styles: [
  ],
})
export class EntriesComponent implements OnInit {

  editForm = this.formBuilder.group({
    title: [Validators.required]
  });

  databaseInformation?: DatabaseInformation;

  entries: Entry[] = [];

  activeEntry?: Entry;

  constructor(private jdsClient: JdsClientService, private entryService: EntryService, private formBuilder: FormBuilder) { }

  ngOnInit(): void {
    this.jdsClient.getDatabaseInformation().subscribe(
      info => this.databaseInformation = info
    );

    this.entryService.query().subscribe(entries => this.entries = entries);
  }

  newEntry() {
    this.editEntry({});
  }

  editEntry(entry: Entry) {
    this.activeEntry = entry;
    this.editForm.reset();
    this.editForm.setValue({ title: entry.title || "" });
  }

  saveEntry() {
    if (this.activeEntry && this.editForm.valid) {
      this.activeEntry.title = this.editForm.value.title;

      if (this.activeEntry.id === undefined) {
        this.entries.push(this.activeEntry);
      }
      this.entryService.save(this.activeEntry).subscribe();
      this.activeEntry = undefined;
    }
  }

  deleteEntry(entry: Entry) {
    const index = this.entries.indexOf(entry);
    if (index >= 0) {
      this.entries.splice(index, 1);
      this.entryService.delete(entry).subscribe();
    }
    if (this.activeEntry === entry) {
      this.activeEntry = undefined;
    }
  }

  testBTree() {
    const nodes: BTreeNode[] = [
      {
        id: "root",
        keys: ["h"],
        values: ["H"],
        children: ["c1", "c2"]
      },
      {
        id: "c1",
        keys: ["b", "d", "f"],
        values: ["B", "D", "F"],
      },
      {
        id: "c2",
        keys: ["m", "n", "o"],
        values: ["M", "N", "O"],
      }

    ];
    const nodesMap: Map<string, BTreeNode> = new Map();
    nodes.forEach(node => nodesMap.set(node.id, node));

    const fetchNode = (id: string): BTreeNode => {
      const node = nodesMap.get(id);
      if (node === undefined) {
        throw new Error("node not found: " + id);
      }
      return node;
    };
    let id = 0;
    const generateId = () => {
      ++id;
      return "" + id;
    };

    let rootId = "root";
    const applyResult = (result: BTreeModificationResult) => {
      rootId = result.newRootId;
      result.newNodes.forEach(node => nodesMap.set(node.id, node));
      result.obsoleteNodes.forEach(node => nodesMap.delete(node.id));
    };

    const tree = new RemoteBTree(3, fetchNode, generateId);

    const chars = "abcdefghijklmnopqrstuvwxyz".split("");
    chars.forEach(key => {
      console.log(key, tree.getValue(key, rootId));
    });

    applyResult(tree.initializeNewTree());

    [...chars].reverse().forEach(key => {
      applyResult(tree.setValue(key, key.toUpperCase(), rootId));
    });

    chars.forEach(key => {
      console.log(key, tree.getValue(key, rootId));
    });
    console.log(nodesMap);
  }

}

<h2>Entries</h2>
<p>Database name: {{databaseInformation?.name}}</p>

<hr>

<div>
  <button (click)="testBTree()">
    Test B-tree
  </button>
  <button (click)="bTreeBenchmark()">
    Benchmark B-tree
  </button>
  <button (click)="bTreeBenchmarkSetup()">
    Benchmark Setup
  </button>
  <button (click)="bTreeBenchmark1()">
    Benchmark 1
  </button>
  <button (click)="bTreeBenchmark2()">
    Benchmark 2
  </button>
  <button (click)="bTreeBenchmark3()">
    Benchmark 3
  </button>
  <button (click)="bTreeBenchmark4()">
    Benchmark 4
  </button>
</div>

<div>
  <input type="text" [(ngModel)]="treeElement">
  <input type="number" [(ngModel)]="treeOrder">
</div>

<div>
  <button (click)="treeInit()">
    init
  </button>
  <button (click)="treeInsert()">
    insert
  </button>
  <button (click)="treeInsertRandom()">
    insert random
  </button>
  <button (click)="treeDelete()">
    delete
  </button>
  <button (click)="treeDelete10()">
    delete 10
  </button>
</div>

<pre>{{treeDump}}</pre>

<hr>

<div *ngFor="let entry of entries">
  <h4>{{entry.title}}</h4>
  <p>id: {{entry.id}}</p>
  <p>version: {{entry.version}}</p>

  <button (click)="editEntry(entry)">
    Edit
  </button>
  <button (click)="deleteEntry(entry)">
    Delete
  </button>
</div>

<hr>

<button (click)="newEntry()">
  New entry
</button>
<div *ngIf="activeEntry">
  <form [formGroup]="editForm" (ngSubmit)="saveEntry()">
    <label>
      Title
      <input type="text" formControlName="title">
    </label>
    <button type="submit" [disabled]="!editForm.valid || editForm.pristine">Save</button>
  </form>
</div>

// src/pages/Entries.vue
<script setup lang="ts">
import { reactive, ref } from "@vue/reactivity";
import { computed } from "@vue/runtime-core";
import type { Entry } from "../shared/entry/entry";
import { EntryService } from "../shared/entry/entry-service";
import type { DatabaseInformation } from "../shared/jds-client";
import { JdsClient } from "../shared/jds-client";
import { getSettings } from "../shared/settings";

const settings = getSettings();
if (settings === undefined || settings.jdsUrl === undefined) {
  throw new Error("jdsUrl not available");
}
const jdsClient = new JdsClient(settings.jdsUrl);
const entryService = new EntryService(settings.jdsUrl);

const databaseInformation = ref<DatabaseInformation>();

const entries = reactive<Entry[]>([]);
const activeEntry = ref<Entry>();

function refreshData() {
  jdsClient.getDatabaseInformation().then(info => databaseInformation.value = info);

  entryService.query().then(result => {
    entries.length = 0;
    entries.push(...result);
  });
}
refreshData();


function newEntry() {
  editEntry({});
}

const formValues = reactive({
  title: ""
})

const formValid = computed(() => formValues.title !== undefined && formValues.title.length > 0);

function editEntry(entry: Entry) {
  activeEntry.value = entry;
  formValues.title = entry.title || "";
}

function saveEntry() {
  if (activeEntry.value && formValid.value) {
    activeEntry.value.title = formValues.title;

    if (activeEntry.value.id === undefined) {
      entries.push(activeEntry.value);
    }
    entryService.save(activeEntry.value);
    activeEntry.value = undefined;
  }
}

function deleteEntry(entry: Entry) {
  const index = entries.indexOf(entry);
  if (index >= 0) {
    entries.splice(index, 1);
    entryService.delete(entry);
  }
  if (activeEntry.value === entry) {
    activeEntry.value = undefined;
  }
}
</script>

<template>
  <h2>Entries</h2>
  <p>Database name: {{ databaseInformation?.name }}</p>

  <hr />

  <div v-for="entry in entries" :key="entry.id">
    <h4>{{ entry.title }}</h4>
    <p>id: {{ entry.id }}</p>
    <p>version: {{ entry.version }}</p>

    <button @click="editEntry(entry)">Edit</button>
    <button @click="deleteEntry(entry)">Delete</button>
  </div>

  <hr />

  <button @click="newEntry()">New entry</button>

  <div v-if="activeEntry">
    <form @submit="saveEntry()">
      <label>
        Title
        <input type="text" v-model="formValues.title" />
      </label>
      <!-- TODO: somehow handle "disabled if pristine"... -->
      <button type="submit" :disabled="!formValid">Save</button>
    </form>
  </div>
</template>

<style scoped>
</style>
