// src/app/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Settings, getSettings, saveSettings } from '../shared/settings';
import { Router } from '@angular/router';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styles: [
  ],
})
export class SettingsComponent implements OnInit {

  settings: Settings;

  constructor(private router: Router) {
    this.settings = getSettings() || new Settings();
  }

  ngOnInit(): void {
  }

  saveSettings(navigate: boolean) {
    saveSettings(this.settings);

    if (navigate) {
      this.router.navigate(['']);
    }
  }

}

<h2>Settings</h2>

<div>
  <label>jds URL:
    <input [(ngModel)]="settings.jdsUrl" placeholder="https://..." />
  </label>
</div>

<div>
  <button (click)="saveSettings(true)">Save</button>
</div>

// src/pages/Settings.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { getSettings, saveSettings, Settings } from "../shared/settings";

const router = useRouter();
const settings = getSettings() || new Settings();

function save(navigate: boolean) {
  saveSettings(settings);

  if (navigate) {
    router.push('/');
  }
}
</script>

<template>
  <h2>Settings</h2>

  <div>
    <label>
      jds URL:
      <input v-model="settings.jdsUrl" placeholder="https://..." />
    </label>
  </div>

  <div>
    <button @click="save(true)">Save</button>
  </div>
</template>

<style scoped>
</style>
